version: '3.6'
# Deploys Spring Music app with in-memory persistence
#
# usage:
# sudo docker-compose build
# sudo docker-compose up

services:

  spring-boot-udacity:
    image: spring-boot-udacity
    build: .
    ports:
      - 8080:8080
    environment:
      - example=my value
    volumes:
      - javatmp:/tmp


volumes:
  # default dir /var/lib/docker/volumes
  javatmp:
