apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes1
  labels:
    app: kubernetes1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes1
  template:
    metadata:
      labels:
        app: kubernetes1
        version: 0.0.1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
    spec:
      containers:
        - name: kubernetes1
          image: swetha29vellampalli/spring-boot-udacity:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080